name: Localize Application Content
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  localize:
    runs-on: ubuntu-latest
    steps:
      - name: Run Locawise Localization
        uses: aemresafak/locawise-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          source-lang-code: 'en'
          file-name-pattern: 'values-{language}/strings.xml'
          target-lang-codes: 'de,es,fr,it,pr-rBR,uk,zh-rCN,ja'
          localization-root-path: 'app/src/main/res/'
          context: |
            You are translating for "FastTrack", a simple app for tracking intermittent fasting.
          glossary: |
            Fast: An instance of an intermittent fast. Fasting is when the user does not each for a period of time.
            Log: The log book of the user's previous fasts.
            Profile: The user's general stats, height, weight, age.
          tone: Be as polite as possible while also being friendly
          llm-model: 'gpt-4o'
      - name: Get commit info
        id: commit-info
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          COMMIT_MSG=$(git log -1 --pretty=%s | tr -d '\n')
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[Bot] Update localization files from commit ${{ steps.commit-info.outputs.sha_short }}"
          title: "[Bot] Localization Update (${{ steps.commit-info.outputs.sha_short }})"
          body: |
            🤖 This PR was automatically created by the locawise workflow.
            Localization files have been updated from commit ${{ steps.commit-info.outputs.sha_short }}.
            Original commit message: "${{ steps.commit-info.outputs.commit_message }}"
          branch: localization-${{ steps.commit-info.outputs.sha_short }}
          base: main
          labels: automated-pr, bot, localization