name: Publish to Play Store

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Decode GitHub Release Keystore
        env:
          GITHUB_RELEASE_ENCODED_KEYSTORE: ${{ secrets.GH_RELEASE_ENCODED_KEYSTORE }}
        run: |
          echo $GITHUB_RELEASE_ENCODED_KEYSTORE | base64 -d > app/gh-release-keystore.jks

      - name: Decode Play Store Keystore (AAB signing)
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > app/keystore.jks

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33-google_apis

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          script: ./gradlew connectedCheck

      - name: Build Signed Release APK (for GitHub Release)
        env:
          KEYSTORE_FILE: gh-release-keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.GH_RELEASE_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.GH_RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.GH_RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Build Release AAB (for Play Store)
        env:
          KEYSTORE_FILE: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: aab-release
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error

  publish-github-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download APK artifact
        uses: actions/download-artifact@v5
        with:
          name: apk-release
          path: app/build/outputs/apk/release

      - name: Get version name
        id: get_version
        run: |
          VERSION_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-play-store:
    name: Publish to Play Store
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Fastlane
        run: |
          gem install fastlane

      - name: Decode service account key
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        run: echo $PLAY_STORE_CONFIG_JSON > play-store-config.json

      - name: Download AAB artifact
        uses: actions/download-artifact@v5
        with:
          name: aab-release
          path: app/build/outputs/bundle/release

      - name: Deploy to Play Store
        run: fastlane deploy
