name: Publish to Play Store

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > app/keystore.jks

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Release AAB
        env:
          KEYSTORE_FILE: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Setup Fastlane
        run: |
          gem install fastlane

      - name: Decode service account key
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        run: echo $PLAY_STORE_CONFIG_JSON > play-store-config.json

      - name: Deploy to Play Store
        run: fastlane deploy
